version: '2'
services:
    patientportal-app:
        image: patientportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://localhost:1433;database=PatientPortal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    patientportal-mssql:
        extends:
            file: mssql.yml
            service: patientportal-mssql
